services:
    pim_reference_data.controller.configuration_rest:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\InternalApi\ReferenceDataConfigurationRestController'
        arguments:
            - '@pim_reference_data.registry'
            - '@pim_internal_api_serializer'
