parameters:
    pim_reference_data.factory.value.reference_data.class:            Akeneo\Pim\Enrichment\Component\Product\Factory\Value\ReferenceDataValueFactory
    pim_reference_data.factory.value.reference_data_collection.class: Akeneo\Pim\Enrichment\Component\Product\Factory\Value\ReferenceDataCollectionValueFactory

services:
    pim_reference_data.factory.product_value.reference_data:
        class: '%pim_reference_data.factory.value.reference_data.class%'
        public: false
        arguments:
            - '@pim_reference_data.repository_resolver'
            - '%pim_reference_data.value.reference_data.class%'
            - 'pim_reference_data_simpleselect'
        tags:
            - { name: pim_catalog.factory.value }

    pim_reference_data.factory.product_value.reference_data_collection:
        class: '%pim_reference_data.factory.value.reference_data_collection.class%'
        public: false
        arguments:
            - '@pim_reference_data.repository_resolver'
            - '%pim_reference_data.value.reference_data_collection.class%'
            - 'pim_reference_data_multiselect'
        tags:
            - { name: pim_catalog.factory.value }
