parameters:
    pim_reference_data.normalizer.indexing.product.reference_data.class: Akeneo\Pim\Enrichment\Component\Product\Normalizer\Indexing\Value\ReferenceDataNormalizer
    pim_reference_data_collection.normalizer.indexing.product.reference_data.class: Akeneo\Pim\Enrichment\Component\Product\Normalizer\Indexing\Value\ReferenceDataCollectionNormalizer

services:
    pim_reference_data.normalizer.indexing.product.reference_data:
        class: '%pim_reference_data.normalizer.indexing.product.reference_data.class%'
        tags:
            - { name: pim_indexing_serializer.normalizer, priority: 90 }

    pim_reference_data_collection.normalizer.indexing.product.reference_data:
        class: '%pim_reference_data_collection.normalizer.indexing.product.reference_data.class%'
        tags:
            - { name: pim_indexing_serializer.normalizer, priority: 90 }
