parameters:
    pim_reference_data.normalizer.configuration.class:       Akeneo\Pim\Structure\Component\Normalizer\InternalApi\ReferenceDataConfigurationNormalizer
    pim_reference_data.normalizer.flat.reference_data.class: Akeneo\Tool\Bundle\VersioningBundle\Normalizer\Flat\ReferenceDataNormalizer

services:
    pim_reference_data.normalizer.configuration:
        class: '%pim_reference_data.normalizer.configuration.class%'
        tags:
            - { name: pim_internal_api_serializer.normalizer }

    pim_reference_data.normalizer.flat.reference_data:
        class: '%pim_reference_data.normalizer.flat.reference_data.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }
